### ISSUE TITLE
Dependence on dplyr?

### ISSUE THREAD

**Issue by jgabry** [jgabry/bayesplot#21]
Currently the use of **dplyr** functions in the **bayesplot** source code is inconsistent. I think it's best to either use it as much as possible or not at all. If the former, then this can wait until after the initial release, but if **dplyr** is to be removed I'd rather not include it as a dependency in the initial release.

**Comment by paul-buerkner** [comment]
I agree that consistency in the usage of **dplyr** makes sense. I am not sure though, why it should matter to the user if you remove the dependency later on, since you only list it under Imports and not under Depends. Thus users will likey not even notice a change in the dependency and it will not affect the behavior of their code.

**Comment by jgabry** [comment]
Yeah I guess what I really meant is that I don't like forcing packages to
be installed (Depends or Imports) if it's not too hard to change the code
so they're not really needed. But you're right that this can be done after
the initial release. I included it in the pre-release checklist because
(knowing myself) if I let it slide until after the release it will be easy
to keep putting it off in favor of doing other things and it might never
happen.

**Comment by jgabry** [comment]
Ok for now I'm going to keep dplyr in Imports and close this issue.
